[build]
  command = "npm run build"
  publish = "dist"  # or "build" for CRA

[[redirects]]
  from = "/api/*"
  to = "https://teams-todoapp.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
